include('/Users/dreevo/IdeaProjects/config-service/Tiltfile')
include('/Users/dreevo/IdeaProjects//menu-service/Tiltfile')
include('/Users/dreevo/IdeaProjects//order-service/Tiltfile')
update_settings(max_parallel_updates=1)